name: yongchoe
favicon: null
layout_spectrum: 0.19065751787275076
typography_spectrum: 0.46956755546852946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
